from images import *

GAME_ITEMS = [("A King's Crown", IMG_A_KINGS_CROWN),
              ("Aegis", IMG_AEGIS),
              ("Awakening Armor", IMG_AWAKENING_ARMOR),
              ("Awakening Armor +1", IMG_AWAKENING_ARMOR_PLUS_1),
              ("Awakening Sword", IMG_AWAKENING_SWORD),
              ("Awakening Sword +1", IMG_AWAKENING_SWORD_PLUS_1),
              ("Black Essence", IMG_BLACK_ESSENCE),
              ("Blue Elixir", IMG_BLUE_ELIXIR),
              ("Caduceus", IMG_CADUCEUS),
              ("Claymore", IMG_CLAYMORE),
              ("Coat of Gold", IMG_COAT_OF_GOLD),
              ("Dark Boots", IMG_DARK_BOOTS),
              ("Dark Gate", IMG_DARK_GATE),
              ("Dark Knight Armor", IMG_DARK_KNIGHT_ARMOR),
              ("Demon Eye", IMG_DEMON_EYE),
              ("Durandal", IMG_DURANDAL),
              ("Earth Armor", IMG_EARTH_ARMOR),
              ("Excalibur", IMG_EXCALIBUR),
              ("Fire Sword", IMG_FIRE_SWORD),
              ("Flamberge", IMG_FLAMBERGE),
              ("Flame Pot", IMG_FLAME_POT),
              ("Freyr's Sword", IMG_FREYRS_SWORD),
              ("Full Helmet", IMG_FULL_HELMET),
              ("Full Plate", IMG_FULL_PLATE),
              ("Gae Bolg", IMG_GAE_BOLG),
              ("Gate", IMG_GATE),
              ("Gold Box", IMG_GOLD_BOX),
              ("Gold Vessels", IMG_GOLD_VESSELS),
              ("Golden Gloves", IMG_GOLDEN_GLOVES),
              ("Golden Rod", IMG_GOLDEN_ROD),
              ("Golden Pot", IMG_GOLDEN_POT),
              ("Green Elixir", IMG_GREEN_ELIXIR),
              ("Guild Hat", IMG_GUILD_HAT),
              ("Gungnir", IMG_GUNGNIR),
              ("Halberd", IMG_HALBERD),
              ("Hydra's Poison Arrows", IMG_HYDRAS_POISON_ARROWS),
              ("Ice Pot", IMG_ICE_POT),
              ("Lævateinn", IMG_LAEVATEINN),
              ("Lance", IMG_LANCE),
              ("Magic Lamp", IMG_MAGIC_LAMP),
              ("Mistilteinn", IMG_MISTILTEINN),
              ("Mithril Armour", IMG_MITHRIL_ARMOUR),
              ("Mithril Sword", IMG_MITHRIL_SWORD),
              ("Mjolnir", IMG_MJOLNIR),
              ("Philosopher's Stone", IMG_PHILOSOPHERS_STONE),
              ("Rapier", IMG_RAPIER),
              ("Red Elixir", IMG_RED_ELIXIR),
              ("Solomon's Key", IMG_SOLOMONS_KEY),
              ("Solomon's Staff", IMG_SOLOMONS_STAFF),
              ("Summoning Letter", IMG_SUMMONING_LETTER),
              ("Tomahawk", IMG_TOMAHAWK),
              ("Training Book", IMG_TRAINING_BOOK),
              ("Wing Boots", IMG_WING_BOOTS)]
