from images import *

# Name, Image, Tier, Importance

GAME_ITEMS = [("A King's Crown", IMG_A_KINGS_CROWN, 1, 1),
              ("Aegis", IMG_AEGIS, 4, 44),
              ("Awakening Armor", IMG_AWAKENING_ARMOR, 2, 35),
              ("Awakening Armor +1", IMG_AWAKENING_ARMOR_PLUS_1, 2, 36),
              ("Awakening Sword", IMG_AWAKENING_SWORD, 2, 11),
              ("Awakening Sword +1", IMG_AWAKENING_SWORD_PLUS_1, 2, 10),
              ("Black Essence", IMG_BLACK_ESSENCE, "?", 50),
              ("Blue Elixir", IMG_BLUE_ELIXIR, 4, 41),
              ("Caduceus", IMG_CADUCEUS, 3, 8),
              ("Claymore", IMG_CLAYMORE, 5, 15),
              ("Coat of Gold", IMG_COAT_OF_GOLD, 4, 43),
              ("Dark Boots", IMG_DARK_BOOTS, 4, 20),
              ("Dark Gate", IMG_DARK_GATE, 4, 23),
              ("Dark Knight Armor", IMG_DARK_KNIGHT_ARMOR, 3, 31),
              ("Demon Eye", IMG_DEMON_EYE, 4, 28),
              ("Durandal", IMG_DURANDAL, 3, 3),
              ("Earth Armor", IMG_EARTH_ARMOR, 5, 33),
              ("Excalibur", IMG_EXCALIBUR, 4, 45),
              ("Fire Sword", IMG_FIRE_SWORD, 4, 16),
              ("Flamberge", IMG_FLAMBERGE, 5, 14),
              ("Flame Pot", IMG_FLAME_POT, "?", 12),
              ("Freyr's Sword", IMG_FREYRS_SWORD, 4, 25),
              ("Full Helmet", IMG_FULL_HELMET, 5, 32),
              ("Full Plate", IMG_FULL_PLATE, 5, 34),
              ("Gae Bolg", IMG_GAE_BOLG, 1, 17),
              ("Gate", IMG_GATE, 4, 22),
              ("Gold Box", IMG_GOLD_BOX, 4, 52),
              ("Gold Vessels", IMG_GOLD_VESSELS, 4, 38),
              ("Golden Gloves", IMG_GOLDEN_GLOVES, 4, 21),
              ("Golden Pot", IMG_GOLDEN_POT, "?", 26),
              ("Golden Rod", IMG_GOLDEN_ROD, 4, 40),
              ("Green Elixir", IMG_GREEN_ELIXIR, 4, 39),
              ("Guild Hat", IMG_GUILD_HAT, 4, 30),
              ("Gungnir", IMG_GUNGNIR, 6, 53),
              ("Halberd", IMG_HALBERD, 3, 19),
              ("Hydra's Poison Arrows", IMG_HYDRAS_POISON_ARROWS, 3, 49),
              ("Ice Pot", IMG_ICE_POT, "?", 37),
              ("Lævateinn", IMG_LAEVATEINN, 2, 24),
              ("Lance", IMG_LANCE, 3, 18),
              ("Magic Lamp", IMG_MAGIC_LAMP, 3, 27),
              ("Mistilteinn", IMG_MISTILTEINN, 2, 2),
              ("Mithril Armour", IMG_MITHRIL_ARMOUR, 2, 5),
              ("Mithril Sword", IMG_MITHRIL_SWORD, 2, 4),
              ("Mjolnir", IMG_MJOLNIR, 3, 29),
              ("Philosopher's Stone", IMG_PHILOSOPHERS_STONE, 3, 9),
              ("Rapier", IMG_RAPIER, 3, 6),
              ("Red Elixir", IMG_RED_ELIXIR, 4, 42),
              ("Solomon's Key", IMG_SOLOMONS_KEY, 4, 46),
              ("Solomon's Staff", IMG_SOLOMONS_STAFF, 4, 47),
              ("Summoning Letter", IMG_SUMMONING_LETTER, 5, 51),
              ("Tomahawk", IMG_TOMAHAWK, 5, 13),
              ("Training Book", IMG_TRAINING_BOOK, 4, 48),
              ("Wing Boots", IMG_WING_BOOTS, 3, 7)]
