import cv2


PAT_IMAGES = "img\\"


IMG_GAME_STATS = cv2.imread(PAT_IMAGES + "game_stats.png")

IMG_A_KINGS_CROWN = cv2.imread(PAT_IMAGES + "a_king's_crown.png")
IMG_AEGIS = cv2.imread(PAT_IMAGES + "aegis.png")
IMG_AWAKENING_ARMOR = cv2.imread(PAT_IMAGES + "awakening_armor.png")
IMG_AWAKENING_ARMOR_PLUS_1 = cv2.imread(PAT_IMAGES + "awakening_sword_plus_1.png")
IMG_AWAKENING_SWORD = cv2.imread(PAT_IMAGES + "awakening_sword.png")
IMG_AWAKENING_SWORD_PLUS_1 = cv2.imread(PAT_IMAGES + "awakening_armor_plus_1.png")
IMG_BLACK_ESSENCE = cv2.imread(PAT_IMAGES + "black_essence.png")
IMG_BLUE_ELIXIR = cv2.imread(PAT_IMAGES + "blue_elixir.png")
IMG_CADUCEUS = cv2.imread(PAT_IMAGES + "caduceus.png")
IMG_CLAYMORE = cv2.imread(PAT_IMAGES + "claymore.png")
IMG_COAT_OF_GOLD = cv2.imread(PAT_IMAGES + "coat_of_gold.png")
IMG_DARK_BOOTS = cv2.imread(PAT_IMAGES + "dark_boots.png")
IMG_DARK_GATE = cv2.imread(PAT_IMAGES + "dark_gate.png")
IMG_DARK_KNIGHT_ARMOR = cv2.imread(PAT_IMAGES + "dark_knight_armor.png")
IMG_DEMON_EYE = cv2.imread(PAT_IMAGES + "demon_eye.png")
IMG_DURANDAL = cv2.imread(PAT_IMAGES + "durandal.png")
IMG_EARTH_ARMOR = cv2.imread(PAT_IMAGES + "earth_armor.png")
IMG_EXCALIBUR = cv2.imread(PAT_IMAGES + "excalibur.png")
IMG_FIRE_SWORD = cv2.imread(PAT_IMAGES + "fire_sword.png")
IMG_FLAMBERGE = cv2.imread(PAT_IMAGES + "flamberge.png")
IMG_FLAME_POT = cv2.imread(PAT_IMAGES + "flame_pot.png")
IMG_FREYRS_SWORD = cv2.imread(PAT_IMAGES + "freyr's_sword.png")
IMG_FULL_HELMET = cv2.imread(PAT_IMAGES + "full_helmet.png")
IMG_FULL_PLATE = cv2.imread(PAT_IMAGES + "full_plate.png")
IMG_GAE_BOLG = cv2.imread(PAT_IMAGES + "gae_bolg.png")
IMG_GATE = cv2.imread(PAT_IMAGES + "gate.png")
IMG_GOLD_BOX = cv2.imread(PAT_IMAGES + "gold_box.png")
IMG_GOLD_VESSELS = cv2.imread(PAT_IMAGES + "gold_vessels.png")
IMG_GOLDEN_GLOVES = cv2.imread(PAT_IMAGES + "golden_gloves.png")
IMG_GOLDEN_POT = cv2.imread(PAT_IMAGES + "golden_pot.png")
IMG_GOLDEN_ROD = cv2.imread(PAT_IMAGES + "golden_rod.png")
IMG_GREEN_ELIXIR = cv2.imread(PAT_IMAGES + "green_elixir.png")
IMG_GUILD_HAT = cv2.imread(PAT_IMAGES + "guild_hat.png")
IMG_GUNGNIR = cv2.imread(PAT_IMAGES + "gungnir.png")
IMG_HALBERD = cv2.imread(PAT_IMAGES + "halberd.png")
IMG_HYDRAS_POISON_ARROWS = cv2.imread(PAT_IMAGES + "hydra's_poison_arrows.png")
IMG_ICE_POT = cv2.imread(PAT_IMAGES + "ice_pot.png")
IMG_LAEVATEINN = cv2.imread(PAT_IMAGES + "laevateinn.png")
IMG_LANCE = cv2.imread(PAT_IMAGES + "lance.png")
IMG_MAGIC_LAMP = cv2.imread(PAT_IMAGES + "magic_lamp.png")
IMG_MISTILTEINN = cv2.imread(PAT_IMAGES + "mistilteinn.png")
IMG_MITHRIL_ARMOUR = cv2.imread(PAT_IMAGES + "mithril_armor.png")
IMG_MITHRIL_SWORD = cv2.imread(PAT_IMAGES + "mithril_sword.png")
IMG_MJOLNIR = cv2.imread(PAT_IMAGES + "mjolnir.png")
IMG_PHILOSOPHERS_STONE = cv2.imread(PAT_IMAGES + "philosopher's_stone.png")
IMG_RAPIER = cv2.imread(PAT_IMAGES + "rapier.png")
IMG_RED_ELIXIR = cv2.imread(PAT_IMAGES + "red_elixir.png")
IMG_SOLOMONS_KEY = cv2.imread(PAT_IMAGES + "solomon's_key.png")
IMG_SOLOMONS_STAFF = cv2.imread(PAT_IMAGES + "solomons_staff.png")
IMG_SUMMONING_LETTER = cv2.imread(PAT_IMAGES + "summoning_letter.png")
IMG_TOMAHAWK = cv2.imread(PAT_IMAGES + "tomahawk.png")
IMG_TRAINING_BOOK = cv2.imread(PAT_IMAGES + "training_book.png")
IMG_WING_BOOTS = cv2.imread(PAT_IMAGES + "wing_boots.png")
